### ISSUE TITLE
can't import CalenderComponent

### ISSUE THREAD

**Issue by Bertus-W** [lbertenasco/ap-ng2-fullcalendar#1]
I only can import Calendar which is an array? why is there no module file?
here I created a module for your component that works:

```
import { CalendarComponent } from './src/calendar/calendar';
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";

@NgModule({
    imports: [
        CommonModule,
    ],
    declarations: [
        CalendarComponent
    ],
    exports: [
        CalendarComponent
    ]
})

export class CalendarModule {

}
```

**Comment by lbertenasco** [comment]
Ready. update your package and it should work.

I've added a barrel so now you can just do:
`import {CalendarModule} from "ap-angular2-fullcalendar";`
or
`import {CalendarComponent} from "ap-angular2-fullcalendar";`
