### ISSUE TITLE
i would like call events by calendar viewDate (start-30-05-2017,end-10-06-2017) i.e how to get calendar view start and end dates @angular2-fullcalendar

### ISSUE THREAD

**Issue by vijj** [lbertenasco/ap-ng2-fullcalendar#12]
![calendar](https://cloud.githubusercontent.com/assets/14217225/26106612/09934a96-3a64-11e7-9e70-c5cddd2d04bd.png)

**Comment by vijj** [comment]
// i would like to send dynamical start end based on calendarview
 this.commonService.get('health/appointment/index?end=2020-04-21&start=2017-01-01').subscribe(
 res => {
this.app=res;
})

**Comment by lbertenasco** [comment]
Hi @vijj you can hook into fullcalendar's [viewRender](https://fullcalendar.io/docs/display/viewRender/) function.
