### ISSUE TITLE
Should @types/moment and @types/node really be dependencies?

### ISSUE THREAD

**Issue by cmyksvoll** [lbertenasco/ap-ng2-fullcalendar#13]
By just including ap-angular2-fullcalendar in my webpack Angular 4 project I get the following compile errors:

> ERROR in [at-loader] TS2688: Cannot find type definition file for 'moment'.
> 
> ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:84:13
>     TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'any', but here has type 'NodeRequire'.

A short-term workaround that I found here is to remove the folders `node_modules/@types/moment` and `node_modules/@types/node`:
https://stackoverflow.com/questions/43802509/type-definition-file-momentjs-import-into-angular2

Moment includes its own type definitions, so `@types/moment` should be removed.

As for `@types/node`... Isn't this actually a devDependency and not a dependency?

**Comment by lbertenasco** [comment]
Hi @cmyksvoll !
`"ap-angular2-fullcalendar": "1.3.0"`
New *v1.3.0* released.
Please try with that and let me know if it's fixed :)

**Comment by cmyksvoll** [comment]
Great :)
No it no longer breaks my Angular project by including it.
