### ISSUE TITLE
How to use next/previous click to get current date

### ISSUE THREAD

**Issue by aneeskodappana** [lbertenasco/ap-ng2-fullcalendar#15]
Is there any way to detect the event when the month is changed

**Comment by lbertenasco** [comment]
Hi @aneeskodappana !
Have you tried adding this to your CalendarOptions?
```
calendarOptions = {
  ....
    viewRender: (view, element) => this.viewRender(view, element),
  ....
}
viewRender(view, element) {
  // logic
}
```
You can use `viewRender`: https://fullcalendar.io/docs/display/viewRender/
