### ISSUE TITLE
Error: CalendarComponent is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by atom-morgan** [lbertenasco/ap-ng2-fullcalendar#16]
**Issue**: I'm currently hitting an error when I try to add this module to my Angular app. The full error reads: `Type CalendarComponent is part of the declarations of 2 modules: CalendarModule and AppModule! Please consider moving CalendarComponent to a higher module that imports CalendarModule and AppModule. You can also create a new NgModule that exports and includes CalendarComponent then import that NgModule in CalendarModule and AppModule.`

**Steps to reproduce**: 

```
1. npm install ap-angular2-fullcalendar --save
2. Import the calendar module as stated in the README
3. Import the calendar component as stated in the README
4. Run `ng serve` and inspect logs
```

**Local Angular setup** via `ng --version`:
```
@angular/cli: 1.1.0
node: 7.6.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3
```

The issue makes sense considering I add `CalendarComponent` to the `declarations` of `AppModule` and that `CalendarComponent` is within the `declarations` and `exports` property of this lib. Is there an easy way around this?

**Comment by lbertenasco** [comment]
Hi @atom-morgan !

Yes, the readme is not clear on this (I'll update it)

You should **only** include `CalendarModule` in your app imports.

**Comment by atom-morgan** [comment]
Thanks! Where do you import `CalendarComponent`? I believe this is still needed somewhere so Angular doesn't complain about an unknown element.

**Comment by lbertenasco** [comment]
You'll need to import `CalendarComponent` if you use:
`@ViewChild(CalendarComponent) myCalendar: CalendarComponent;`
