### ISSUE TITLE
Please update step for importing css

### ISSUE THREAD

**Issue by kktam** [lbertenasco/ap-ng2-fullcalendar#18]
the step for importing css needs to be updated.

```
@import "fullcalendar/fullcalendar.min.css";
```

needs to be changed to 

```
@import "../node_modules/fullcalendar/dist/fullcalendar.min.css";
```
due to the distribution path inside the fullcalendar module.

Also in order for import to pick up from the node_modules, this implies the Application project also need to import fullcalendar project itself.

```
npm install --save fullcalendar
```

Note: is there a way around this? it would be nicer if somehow the component project can bundle fullcalendar.io itself and does not require the application to import the dependency of this library every time.

**Comment by lbertenasco** [comment]
Are we sure about this?
Do you have a sample repo to showcase the `@import` error?

**Comment by thecodehunter** [comment]
@kktam  is right about the css

**Comment by lbertenasco** [comment]
Ok, just updated the `README.md` to include this case!

[commit](https://github.com/lbertenasco/ap-ng2-fullcalendar/commit/9d526a8884ef443109b60fdaa80881f9f14a49a9)
