### ISSUE TITLE
ap-ng2-fullcalendar cannot start from App using angular-cli

### ISSUE THREAD

**Issue by kktam** [lbertenasco/ap-ng2-fullcalendar#19]
I have created a demo from app from the new angular-cli, that uses now Angular 4.0.0. 
I have follow your readme and added the component as view child, but the view child came out to be undefined or null, and the ap-ng2-fullcalendar cannot start.

I have included demo in my github [https://github.com/kktam/ap-ng2-fullcalendar-app](url).
Your help is most appreciated.

**Comment by lbertenasco** [comment]
This project is working fine on my end.
Am I missing something?

**Comment by kktam** [comment]
No. I verified it is my environment. the version I checked in now got the fix that will work with latest angular-cli generating 4.0.0 project.  In my case, I do have to clean cache and start over before things works. Sorry for the confusion.

**Comment by lbertenasco** [comment]
Glad to hear everything is working 😄 !
Closing the issue.
