### ISSUE TITLE
How to Freeze Calendar Dates in Angular2

### ISSUE THREAD

**Issue by manibonthu** [lbertenasco/ap-ng2-fullcalendar#20]
I want to block Saturday and Sunday by using Angular 2.

Can any one help me to solve this problem.

Thanks in Advance.

**Comment by lbertenasco** [comment]
Hi @mani3202 !
You can use the property [hiddenDays](https://fullcalendar.io/docs/display/hiddenDays/)

for example to hide both Saturday & Sunday you can add:
`hiddenDays: [0,6]` in your `calendarOptions` Object.

Let me know if this helps.

To disable those days you should look into:
[dayRender](https://fullcalendar.io/docs/display/dayRender/)
[dayClick](https://fullcalendar.io/docs/mouse/dayClick/)
