### ISSUE TITLE
@types/jquery problem 

### ISSUE THREAD

**Issue by qwe852147** [lbertenasco/ap-ng2-fullcalendar#23]
I have a trouble after install this module

I get this error

`node_modules/@types/jquery/index.d.ts (3782,13): Subsequent variable declarations must have the same type.  Variable '$' must be of type 'any', but her
e has type 'JQueryStatic'.)`

There has any solution to deal this?

**Comment by lbertenasco** [comment]
Hi @qwe852147 !
Please share your angular versions: (copy and paste `ng -v`).
And could you also share the code where you are getting this error?
Thanks!

**Comment by qwe852147** [comment]
I find I declare $ to any some where  without @type/jquery before I install this module.
