### ISSUE TITLE
jquery import issues when multiple calendar exist in component.

### ISSUE THREAD

**Issue by davvit** [lbertenasco/ap-ng2-fullcalendar#24]
![question2](https://user-images.githubusercontent.com/4433698/27991359-796b2394-6439-11e7-991a-ae5778a636fe.png)
![question](https://user-images.githubusercontent.com/4433698/27991358-796824be-6439-11e7-99e0-9ab941c1c6dd.png)

I added 2 fullCalenders (https://fullcalendar.io/) (with different views) in one component and i am getting jquery error. I get this error even if i separate the calender in two different components and added to third component like this.
```
//thirdComponent template
<div>
  <app-day-calender></app-day-calender>
  <app-calender></app-calender>
</div>
```
If i had one component with just one calendar everything works fine (no errors and bootstrap modal works - the big red error happens when i click on the events - bootstrap modal is used to show the event data during eventClick event).  I think the issue is with jquery being loaded twice for each calendar or smtn like that.

i am not using the component as it is in this repo. Instead i am writing my own following the setup in this repo. Here is my calendar init.
```
 ngAfterViewInit() {
    setTimeout(() => {
      // console.log("100ms after ngAfterViewInit ");
      $('#dailyCalContainer').fullCalendar(this.dailyCalOptions);
      $('#fullCalContainer').fullCalendar(this.fullCalOptions);
    }, 100)
  }
```
here is the html
```
<div ">
  <div id='dailyCalContainer' style="width:20%;padding:10px;float:left; height:1000px;overflow-y:hidden;"></div>
  <div class="center" id='fullCalContainer' style="width:70%;float:left;justify-content: center;padding:10px;"></div>
</div>
```
As this issue is not directly related to this repo i posted the question to SO as well.
[ https://stackoverflow.com/q/44990890/1745477?stw=2](url)

**Comment by lbertenasco** [comment]
I see this was resolved on [stackoverflow.com/q/44990890/1745477?stw=2](https://stackoverflow.com/q/44990890/1745477?stw=2)
I'm closing the issue 👍
