### ISSUE TITLE
How to call functions

### ISSUE THREAD

**Issue by androidseb25** [lbertenasco/ap-ng2-fullcalendar#26]
How i can call a function like select in my component?
When i try the example like this

` select: function (start, end) {alert('selected :D');}`

my IDE says it's an unused property

**Comment by lbertenasco** [comment]
Hi @androidseb25 !

Try using an [Arrow Function](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) `select: (start, end) => {alert('selected :D');}`

Let me know if this helped :)

**Comment by androidseb25** [comment]
@lbertenasco thx it work perfectly :D
