### ISSUE TITLE
fill events with API data from observable

### ISSUE THREAD

**Issue by hnitzsche** [lbertenasco/ap-ng2-fullcalendar#27]
can someone tell me if it's possible to display events from API data that come as Observable?
API data (in fullcalendar event syntax) reaches my component, but I struggle to display it.

**Comment by lbertenasco** [comment]
Hi @swungdash !

Thanks for reaching out, sadly this is not an issue so you should try to ask on [stackoverflow.com](https://stackoverflow.com/).

Also you can check the official documentation: [fullcalendar.io/docs](https://fullcalendar.io/docs/).

That said, if you would like to share more information about this you can add a snippet of code showing where you need assistance.

Have a good day!

**Comment by tiddy** [comment]
This is what I used, I was unable to get the ViewChild to call events without jQuery.  I should also note that the 'addEventSource' call in the init data callback is required to squash the "FullCalendar does not render events" when it initializes before the data is available.  

```typescript
        import * as $ from 'jquery';
        //Stuff//
        calendarOptions: Object = {}
	header: Object = {right: 'month listMonth today prev,next'};

	ngOnInit(){
	  this.leaveService.feed().subscribe(
	    data => {
	      this.calendarOptions = {events: data, header: this.header};
	      $('angular2-fullcalendar').fullCalendar('addEventSource', {events: data});
	     }
           );
         }
```
