### ISSUE TITLE
Calling function 'ɵmakeDecorator', function calls are not supported. 

### ISSUE THREAD

**Issue by hesyar** [lbertenasco/ap-ng2-fullcalendar#3]
Hello,

I get this error message when using this library and calling ng serve.

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /my/project/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol CalendarModule in /my/project/node_modules/ap-angular2-fullcalendar/angular2-fullc
alendar.ts, resolving symbol CalendarModule in /my/project/node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.ts

After this error, I change a file and it compiles it again automatically. After the second compilation the app works fine. Can you help me please?

**Comment by lbertenasco** [comment]
Hi @hasher what version of Angular and angular-cli are you using?

**Comment by lbertenasco** [comment]
@hasher just released version `1.1.7` please update and check if the issue was resolved.

**Comment by hesyar** [comment]
@lbertenasco I updated it but the problem still occurs. 

I'm using the following version:
angular-cli 1.0.0-beta.32.3
angular 2.4.0

**Comment by hesyar** [comment]
I updated the angular-cli to 1.0.0 and angular itself to 4.0.1 but the problem still occurs

**Comment by hesyar** [comment]
I created a pull request which solves this problem. Please check ;)

**Comment by lbertenasco** [comment]
Thanks @hasher.
Closing this issue.
