### ISSUE TITLE
How to use Select Callback?

### ISSUE THREAD

**Issue by RZR666** [lbertenasco/ap-ng2-fullcalendar#30]
Hi,

I've got this loaded in an Ionic 3 application, it works well but for some reason I had to copy the CSS directly, none of the import instructions worked for me.

How do I add the select callback to the calendar?

Thanks

**Comment by lbertenasco** [comment]
Hi @RZR666 
I assume you were able to fix this issue 👍 
Feel free to open a new one if you need further assistance
