### ISSUE TITLE
How to use custom buttons?

### ISSUE THREAD

**Issue by RZR666** [lbertenasco/ap-ng2-fullcalendar#31]
Hi,

I've got the Calendar up and running in Ionic 3 and it works great but I'm trying to use custom buttons for the next/prev events and I'm running into an issue...

@ViewChild('calendar') myCalendar: CalendarComponent;
myCalendar.fullCalendar('prev');

@ViewChild('calendar', { read: ElementRef }) myCalendar: ElementRef;
myCalendar.nativeElement.fullCalendar('prev');

Cannot read property 'fullCalendar' of undefined

any help appreciated.

**Comment by lbertenasco** [comment]
Hi @RZR666 !
If you use `@ViewChild`, you need to make sure the component is initialized before.

You can do this by listening to the `initialized` output.

**Comment by RZR666** [comment]
Hi, yes even after the initialised event has occurred, I'm still receiving the following,

Cannot read property 'fullCalendar' of undefined

Thanks

**Comment by lbertenasco** [comment]
Could you paste the full html + ts content here?
So I can see what's the issue.

**Comment by RZR666** [comment]
```
<ion-content>

        <button ion-button id="myButton" (click)="clickedNow();">Now</button></ion-col>
        <button ion-button id="myButton" (click)="clickedPrev();">Prev</button></ion-col>
        <button ion-button id="myButton" (click)="clickedNext();">Next</button></ion-col>

      <angular2-fullcalendar #myCalendar [options]="calendarOptions" (initialized)="onCalendarInit($event)"></angular2-fullcalendar>

</ion-content>
```

and the ts

```
export class BookAHoliday {

  @ViewChild('calendar') myCalendar: CalendarComponent;

  ionViewDidLoad() {

   this.calendarOptions = {
      height: 'auto',
      fixedWeekCount: false,
      defaultDate: '2017-08-12',
      editable: false,
      selectable: true,
      dragScroll: true,
      selectOverlap: false,
      unselectCancel: "#myButton"
    };
  }


  clickedNow()
  {
    this.myCalendar.fullCalendar('today');
  }


  clickedPrev()
  {
    this.myCalendar.fullCalendar('prev');
  }


  clickedNext()
  {
    this.myCalendar.fullCalendar('next');
  }
```

Thanks.

**Comment by lbertenasco** [comment]
Oh, the `@ViewChild('calendar')` attribute works by searching the element with that **id**
[@ViewChild Doc](http://learnangular2.com/viewChild/)
In your case, you should rename the html component too.
`#myCalendar` to `#calendar`

**Comment by RZR666** [comment]
oh eh, how did I miss that, ha.

Superb mate, works great now, thanks for the help.
