### ISSUE TITLE
How to get current date when change month or day

### ISSUE THREAD

**Issue by joaquin595** [lbertenasco/ap-ng2-fullcalendar#33]
Hello, 

I was wondering if it is possible to get the current date when changing the month or day, since the fullcalendar () function returns void and I can not extract the month from the Moment that it should return.

**Comment by lbertenasco** [comment]
Hi @joaquin595 you can hook into the [viewRender](https://fullcalendar.io/docs/display/viewRender/) callback on your calendarOptions.

```js
    calendarOptions:Object = {
        ....
        viewRender: (view, element) => this.onViewRender(view, element),
        ....
    }

    onViewRender(view, element) {
        console.log(view.intervalStart);
        console.log(view.intervalEnd);
    }
```
