### ISSUE TITLE
Unexpected value 'CalendarComponent' ... Please add a @Pipe/@Directive/@Component 

### ISSUE THREAD

**Issue by werwuifi** [lbertenasco/ap-ng2-fullcalendar#34]
Hi all,
I am trying to get the calendar component running with Angular 4 and followed the "Getting Started" section, however I am getting 
`Uncaught Error: Unexpected value 'CalendarComponent' declared by the module 'MyModule'. Please add a @Pipe/@Directive/@Component annotation`
for including
```
declarations: [
    MyComponent,
    CalendarComponent
],
```
regardless whether I am importing from 'angular2-fullcalendar/src/calendar/calendar' or 'ap-angular2-fullcalendar'
Also adding the CalendarModule to the imports section does not help.
Can you give me advice on what is wrong here?
Thx
w

**Comment by lbertenasco** [comment]
Hi @werwuifi are you using Angular CLI?
Could you show me your package.json?
You should always import it from the module `ap-angular2-fullcalendar`

**Comment by jchavarria1983** [comment]
Hi I have the same issue.  Did you find the fix ? @werwuifi @lbertenasco

**Comment by werwuifi** [comment]
Hi *,
Thanks for the replies but couldn't get it running. I followed the instructions but get the above error message. If I use CalendarModule instead of CalendarComponent, the error message changes to 
`Uncaught Error: Unexpected value 'CalendarModule' imported by the module 'MyModule'. Please add a @NgModule annotation.`
It's the same btw. with angular2-fullcalendar.
Cheers,
w

**Comment by jchavarria1983** [comment]
hi, now I have another error:

ERROR in C:/wamp64/www/ng2-admin/node_modules/ap-angular2-fullcalendar/node_modules/@types/fullcalendar/index.d.ts (154,27): Namespace 'moment' has no exported member 'DurationInputArg1'.

and I dont understand what happen I wasted a lot of time trying to fix it  @werwuifi 

Fixed but now I have another error:

ERROR TypeError: specialTokens[fakePart.substring(...)] is not a function
    at renderFakeFormatStringParts (fullcalendar.js:1800)
    at renderFakeFormatString (

**Comment by rseiffert** [comment]
Hi everyone, same here. If I try to import the `calendarComponent` it gives me 
`Uncaught Error: Unexpected value 'CalendarComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.`
if I try to import `calendarModule` it shows
`Uncaught Error: Unexpected value 'CalendarModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`

Angular version is 4.2.6

My (shortened - without dev-dependencies) package.json looks like this (this is a jhipster-application):

> {
  "name": "xxx",
  "version": "0.0.0",
  "description": "Description for xxx",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules"
  ],
  "dependencies": {
    "angular/common": "4.2.6",
    "angular/compiler": "4.2.6",
    "angular/core": "4.2.6",
    "angular/forms": "4.2.6",
    "angular/http": "4.2.6",
    "angular/platform-browser": "4.2.6",
    "angular/platform-browser-dynamic": "4.2.6",
    "angular/router": "4.2.6",
    "ng-bootstrap/ng-bootstrap": "1.0.0-alpha.28",
    "ap-angular2-fullcalendar": "^1.3.1",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "2.4.1",
    "font-awesome": "4.7.0",
    "jquery": "3.2.1",
    "ng-jhipster": "0.2.7",
    "ng2-webstorage": "1.8.0",
    "ngx-cookie": "1.0.0",
    "ngx-infinite-scroll": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "sockjs-client": "1.1.4",
    "swagger-ui": "2.2.10",
    "tether": "1.4.0",
    "webstomp-client": "1.0.6",
    "zone.js": "0.8.13"
  },
  "engines": {
    "node": ">=6.9.0"
  }
}

Any idea?

**Comment by lbertenasco** [comment]
Hi! please check the demo project https://github.com/lbertenasco/ap-ng2-fullcalendar-demo
