### ISSUE TITLE
Select not working

### ISSUE THREAD

**Issue by KyDenZ** [lbertenasco/ap-ng2-fullcalendar#35]
Hello

The select option is triggered at the start of the component but does not unlock at the time of selection in the calendar

Thanks

**Comment by lbertenasco** [comment]
Hi @KyDenZ !
Could you add a code example showcasing the issue?

**Comment by KyDenZ** [comment]
Yes, here is the code : 

```
calendarOptions: any = {
    locale: 'fr',
    defaultView: 'agendaWeek',
    timezone: 'local',
    height: 'auto',
    fixedWeekCount: false,
    defaultDate: '2017-08-12',
    buttonIcons: false, // show the prev/next text
    weekNumbers: true,
    navLinks: true, // can click day/week names to navigate views
    editable: true,
    eventLimit: true, // allow "more" link when too many events
    events: [],
    select: (start, end, allDay) => {
      console.log("test");
    },
    defaultEventMinutes: 120,
    axisFormat: 'HH:mm',
    minTime: 0
  };
```

The console log is shown once only when the page loads, but when I click on an hour I do not have an event that is created. Otherwise the other functions works well

thanks

**Comment by lbertenasco** [comment]
Try with [eventClick](https://fullcalendar.io/docs/mouse/eventClick/) callback instead of `select`.
Or read the [Fullcalendar Docs](https://fullcalendar.io/docs/) for more info
