### ISSUE TITLE
Not working on modal

### ISSUE THREAD

**Issue by anil1712** [lbertenasco/ap-ng2-fullcalendar#36]
Hi,

I am using this library for modal
https://vmware.github.io/clarity/documentation/modals
but it seems the calendar is not rendering into the modal, is anyone having the same issue, because on page its working completely fine.

Please let me if someone has any solution for the same.

Thanks,
Anil

**Comment by lbertenasco** [comment]
Hi @anil1712 !
Do you have any sample repo showcasing the issue?

**Comment by anil1712** [comment]
I implemented it in my project only but code snippet will be look like this.

```
<clr-modal [(clrModalOpen)]="opened" [clrModalClosable]="false">
    <h3 class="modal-title">No "x" in the top-right corner</h3>
    <div class="modal-body">
       <angular2-fullcalendar [options]="calendarOptions" (initialized)="onCalendarInit($event)"></angular2-fullcalendar>
    </div>
</clr-modal>
```

**Comment by anil1712** [comment]
@lbertenasco How can I add right click (context menu) support in your calendar?

Please share me any reference link if you have.

**Comment by lbertenasco** [comment]
You can check the documentation of full calendar: https://fullcalendar.io/docs/

**Comment by lbertenasco** [comment]
And about the modal, I'm not sure the issue is related to `ap-ng2-fullcalendar`
