### ISSUE TITLE
issue with locale. (only with header Buttons)

### ISSUE THREAD

**Issue by alan345** [lbertenasco/ap-ng2-fullcalendar#40]
Hi!
Thanks for this awesome package! Very useful!
I have an issue with locale and I could not figure it what is wrong!
I Want to translate in french. It works except for the buttons in header:
![image](https://user-images.githubusercontent.com/15246526/30096347-c0ff966e-928c-11e7-9d48-9fd3e7b2328c.png)

Here you have my config:
```
calendarOptions: Object = {
    timezone: 'local',
    height: 550,
    selectable: true,
    firstDay: 1,
    minTime: "06:00:00",
    maxTime: "22:00:00",
    locale: 'fr',
    slotLabelFormat: "HH:mm",
    allDaySlot: false,
    nowIndicator: true,
    businessHours: {
      dow: [1, 2, 3, 4, 5],
      start: '10:00',
      end: '18:00',
    },
    header: {
      left: 'title',
      center: '',
      right: 'today prev,next month,agendaWeek,listWeek'
    }
]
```

I have tried in other langs, having same issues. Header buttons are always in english.
Thanks!

**Comment by lbertenasco** [comment]
Hi @alan345 !
Please check [buttonText](https://fullcalendar.io/docs/text/buttonText/) docs.

Let me know if this works for you :)
