### ISSUE TITLE
CalendarComponent part of 2 decalarating Modules

### ISSUE THREAD

**Issue by Madtek** [lbertenasco/ap-ng2-fullcalendar#41]
Hi

I try to use this component in a Angular 4 App. It works on "ng serve" but on "ng build" I got this:

ERROR in Type CalendarComponent in 
C:/app/node_modules/ap-angular2-fullcalendar/src/calendar/calendar.d.ts
 is part of the declarations of 2 modules: 
 CalendarModule in 
C:/app/node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.d.ts
 and AppModule in
C:/app/src/app/app.module.ts!
 
 Please consider moving CalendarComponent in 
C:/app/node_modules/ap-angular2-fullcalendar/src/calendar/calendar.d.ts
 to a higher module that imports CalendarModule in 
C:/app/node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.d.ts
 and AppModule in 
C:/app/src/app/app.module.ts.
 
 You can also create a new NgModule that exports and includes CalendarComponent in 
C:/app/node_modules/ap-angular2-fullcalendar/src/calendar/calendar.d.ts
 then import that NgModule in CalendarModule in 
C:/app/node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.d.ts
 and AppModule in 
C:/app/src/app/app.module.ts.

If I remove the Component declaration in my app.module.ts, it doesnt work anymore (of course) 
Iam still new to angular4/2 and dont understand the whole "Module" workflow.

How can I get a clean solution for this?

**Comment by lbertenasco** [comment]
Hi @Madtek !
Can you share a snippet of code that shows where the error is?
Thanks!

**Comment by JoeriShoeby** [comment]
I'm running into the same issues. When installing the package and importing the component + adding to AppModule' declarations array, it throws a:

`Error: Unexpected value 'CalendarComponent' declared by the module 'AppModule'`

When importing the CalendarModule and add it to AppModule' imports array, it throws a:

`Error: Unexpected value 'CalendarModule' imported by the module 'AppModule'`

**Comment by lbertenasco** [comment]
Hi @JoeriShoeby !
Could you share the code where you are importing both the module and the component  so I can check for errors?
Thanks!

**Comment by JoeriShoeby** [comment]
```
import { NgModule, ApplicationRef } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { CalendarComponent, CalendarModule } from 'ap-angular2-fullcalendar';


@NgModule({
  imports: [
    BrowserModule,
    CalendarModule
  ],
  declarations: [
    AppComponent,
    CalendarComponent,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
  
}

```

Note: I've tried importing component and module seperate, and together. Errors appear the same as in previous comment.

**Comment by Madtek** [comment]
Sry my late answere. 
I found my solution. 3 steps:
1. remove the Calendar component declaration form your app.module.ts. 
2. import the Calendar module in your app.modules.ts
3. remove  `(initialized)="onCalendarInit($event)` from your component implementation in the .html.

Hope it helps you out.

**Comment by JoeriShoeby** [comment]
This will result in error as mentioned in first comment: 

`Error: Unexpected value 'CalendarModule' imported by the module 'AppModule'`

I am not even reaching step 3 as Angular does not compile during the given error.

**Comment by lbertenasco** [comment]
Hi @JoeriShoeby !

Are you using angular-cli?
If so, what version do you have? `ng -v`

**Comment by SebastianGiro** [comment]
@JoeriShoeby Normally that error happens with syntaxis errors or importing things in bad places. Please check: https://stackoverflow.com/questions/39265561/error-unexpected-value-undefined-imported-by-the-module

(For example you had two commas in your declarations, I don't know if is that tho)

**Comment by lbertenasco** [comment]
@Madtek & @JoeriShoeby Please check the demo project https://github.com/lbertenasco/ap-ng2-fullcalendar-demo
