### ISSUE TITLE
FullCalendar “Background Events”

### ISSUE THREAD

**Issue by evdigitech** [lbertenasco/ap-ng2-fullcalendar#42]
Need a little help with something. I am using your FullCalendar library in my project. I would like to have the ability to select "Background Events" with the help of dragging even when the Main Events are above that . These Main Events should not stop the selection of Background Events. Currently it is stopping the Background Events for getting selected.

I would like it to be something like this: 
1) User will start dragging and selecting the Background Events. It will change to Orange Color.
2) When Main Events comes, then the current Main Event of Full Calendar interrupts the dragging functionality. I don't want Main Event to interrupt Background Event selection.
3) I can select Background Event irrespective of Main Events position(whether Main Events is present or not on top of Background Events)

Any help would be highly appreciated.

![screen shot 2017-09-18 at 1 57 42 pm](https://user-images.githubusercontent.com/29534100/30533908-5ff73b96-9c79-11e7-809d-68461bf4398a.png)

**Comment by lbertenasco** [comment]
@evdigitech Any news on this?
I'm closing this issue since it's not related to the library.
Feel free to reopen it :)
