### ISSUE TITLE
Error in Development

### ISSUE THREAD

**Issue by lanzosuarez** [lbertenasco/ap-ng2-fullcalendar#43]
bg-serve is good, build when run on the browser, it throws and error of

ERROR Error: Uncaught (in promise): Error: Unexpected value 'CalendarComponent' declared by the module 'AdminModule'. Please add a @Pipe/@Directive/@Component annotation.
Error: Unexpected value 'CalendarComponent' declared by the module 'AdminModule'. Please add a @Pipe/@Directive/@Component annotation.

ANGULAR VERSIONS IS ON: 4.4.4 AND CLI IS 1.4.4

**Comment by lbertenasco** [comment]
Hi @lanzosuarez !
You can check the demo project at https://github.com/lbertenasco/ap-ng2-fullcalendar-demo
You should probably include `CalendarModule` instead of `CalendarComponent`
