### ISSUE TITLE
Implementation of scheduler

### ISSUE THREAD

**Issue by aces-tm** [lbertenasco/ap-ng2-fullcalendar#48]
Is it possible to add fullcalendar-scheduler using this component? Where am I suppoded to import scheduler.js and jquery-ui?

Thanks!

**Comment by lbertenasco** [comment]
Hi @acessoftware !
You can try to require both files in your `main.ts` 
This question is not related to an issue on the package so I'll close the issue.
Feel free to re-open it :)
