### ISSUE TITLE
critical dependency: the request of a dependency is an expression 

### ISSUE THREAD

**Issue by Adambs** [lbertenasco/ap-ng2-fullcalendar#49]
Hi, 
I upgrade to angular 5, I solved all issues but an error in ap-angular2-fullcalendar library  "critical dependency: the request of a dependency is an expression " . I tried to reinstall everything from scratch many times in different ways but nothing help. 
Please help me and don't assume I know where all the files located.  
![image](https://user-images.githubusercontent.com/13707440/32431066-9725b7be-c2da-11e7-97b0-d2984f3bf4b3.png)

**Comment by lbertenasco** [comment]
Hi @Adambs !
Please upgrade to `ap-angular2-fullcalendar@1.3.3` and check if the issue is fixed.

**Comment by ghost** [comment]
Hey,
I updated to the latest version - 1.3.3 and got this in the console.log, preventing the app from loading:

`Uncaught Error: Unexpected value 'CalendarComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (compiler.js:466)
    at eval (compiler.js:15136)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15118)
    at JitCompiler._loadModules (compiler.js:33484)
    at JitCompiler._compileModuleAndComponents (compiler.js:33445)
    at JitCompiler.compileModuleAsync (compiler.js:33361)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:230)
    at PlatformRef.bootstrapModule (core.js:5443)
    at eval (main.ts:11)`

 That's a familiar error to me, it happens a lot and usually update to @latest and somehow it gets solved,
But not this time...

**Comment by lbertenasco** [comment]
Hi @Shukarity !
Can you add a snippet of code showing where you are using `CalendarComponent`?
Thanks!

**Comment by ghost** [comment]
`declarations: [
    AppComponent,
    HomeComponent,
    CalendarComponent,
    CalendarViewComponent, //<--- the component which holds the @ViewChild, settings etc`

**Comment by lbertenasco** [comment]
You should be able to use `CalendarComponent` as a ViewChild without adding it into `declarations` it should suffice to only import `CalendarModule` in your imports: [].
