### ISSUE TITLE
error in calendar module 

### ISSUE THREAD

**Issue by huliumin** [lbertenasco/ap-ng2-fullcalendar#51]
hi,

I tried the new version with angular5, i get a strange error.
how to produit it:
1. ng new newTest
2. install ap-ng2-fullcalendar module
3. add the module like the guide
4. ng serve
5. open the explorer(chrome) for localhost:4200
6. get a error in js console
![image](https://user-images.githubusercontent.com/31159182/32538134-5140f16e-c465-11e7-929c-bb5129f57a15.png)

**Comment by nico13051995** [comment]
Hi, yes I have this issue too

**Comment by cristitodoran** [comment]
I can confirm.

**Comment by lbertenasco** [comment]
Hi @huliumin @nico13051995 @cristitodoran !
Just released `ap-angular2-fullcalendar@1.3.4` and tried it with a brand new `Angular CLI: 1.5.0` project.
Please let me know if it's fixed for you as well.
