### ISSUE TITLE
Title UndefinedUndefined

### ISSUE THREAD

**Issue by jfillipe** [lbertenasco/ap-ng2-fullcalendar#52]
I´ve been updated, and i get this.
All view´s i get this.

![image](https://user-images.githubusercontent.com/28539354/32578920-3a7ed37c-c4c6-11e7-8635-1fc55cf136d8.png)

Any ideas?
It´s not only this view, on events in Week View too. He show event time begin, undefinedundefined and title.

:'(

I try everything e nothing.

Thanks guys =)

**Comment by lbertenasco** [comment]
Hi @jfillipe !
Please update to `ap-angular2-fullcalendar@1.3.5` and let me know if it's fixed! Thanks!

**Comment by jfillipe** [comment]
@lbertenasco I´ve been updated and nothing. I updated too Angular to v5, FullCalendar to 3.6.2 and nothing too...

:'(

**Comment by lbertenasco** [comment]
@jfillipe Are you using a custom language on your Calendar?
Can you also add more details like code snippets so I can get a better idea on where the issue might be?
Thanks!

**Comment by KiranWorks1061** [comment]
Hi,

Any solution for this issue??

**Comment by jfillipe** [comment]
`events: [],
      businessHours: [],
      eventConstraint: 'businessHours',
      height: 650,
      editable: true,
      fixedWeekCount : false,
      locale: 'pt-br',
      buttonText: {
        today:     'hoje',
        month:     'mensal',
        week:      'semanal',
        day:       'dia',
        listMonth: 'mês',
        listWeek:  'semana',
        listDay:   'dia',
      },
      header: {
        left: 'prev,next listMonth,listWeek,listDay',
        center: 'title',
        right: 'today,month,agendaWeek',
      },
      allDaySlot: false,
      slotDuration: '00:15:00',
      slotLabelFormat: 'HH:mm',
      slotEventOverlap: false,
      scrollTime: '00:30:00',
      noEventsMessage: 'Não há agendamentos para esta data',
      nowIndicator: true,
      timeFormat: 'HH:mm',
      displayEventTime: true,
      columnFormat: 'ddd DD/MM',
      selectOverlap: false,
      selectConstraint: 'businessHours',
      navLinks: true,
      eventOverlap: false,
      eventDurationEditable: false,
    };`

**Comment by lbertenasco** [comment]
@KiranWorks1061 as @jfillipe points you can manually add the text on the calendar options :)

**Comment by jfillipe** [comment]
Sorry, but can you show us one example? Very thanks!!

**Comment by lbertenasco** [comment]
```
 calendarOptions:Object = {
      height: 'parent',
      fixedWeekCount : false,
      defaultDate: '2016-09-12',
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: [],
      buttonText: {... }
      ...
    };
```
[buttonText](https://fullcalendar.io/docs/text/buttonText/)
[monthNames](https://fullcalendar.io/docs/text/monthNames/)
[monthNamesShort](https://fullcalendar.io/docs/text/monthNamesShort/)
[dayNames](https://fullcalendar.io/docs/text/dayNames/)
[dayNamesShort](https://fullcalendar.io/docs/text/dayNamesShort/)


**IMPORTANT!**
If you need more assistance with custom locale languages you can check [the official documentation](https://fullcalendar.io/docs/text/locale/)

I'm keeping this issue closed since it appears to be not related to the package.
Feel free to re-open it and comment if you need more help :)
