### ISSUE TITLE
Property 'length' does not exist on type 'void'.

### ISSUE THREAD

**Issue by vichui** [lbertenasco/ap-ng2-fullcalendar#53]
When use method fullCalendar('clientEvents'), it will return a void type object and made below code cannot compile with error Property 'length' does not exist on type 'void'.
var selectedEvents= this.fullCalendar('clientEvents');
 for( var i=0 ; i < selectedEvents.length;i++){
...
}

I find the way to fix is change file calendar.ts line 35 from 
fullCalendar(...args: any[])  to fullCalendar(...args: any[]) : any

but I don't know how to submit using git.

**Comment by lbertenasco** [comment]
Hi @vichui !
Please update to `ap-angular2-fullcalendar@1.3.5` and let me know if it's fixed! Thanks!
