### ISSUE TITLE
error with 1.3.5

### ISSUE THREAD

**Issue by huliumin** [lbertenasco/ap-ng2-fullcalendar#54]
test with lastest 1.3.5, put 
`<angular2-fullcalendar ></angular2-fullcalendar>`

in app.component.html of a new created angular5 project, get this error : 
![image](https://user-images.githubusercontent.com/31159182/32612179-e6f39d4e-c567-11e7-93d1-615d56c24848.png)

**Comment by lbertenasco** [comment]
Hi @huliumin are you using ng-cli?
If so can you paste `ng -v` here?

**Comment by huliumin** [comment]
![image](https://user-images.githubusercontent.com/31159182/32614556-ce951e7a-c56d-11e7-9cb5-2255490a7913.png)

**Comment by huliumin** [comment]
no more error when I reinstall the component.
