### ISSUE TITLE
I got a doubt about refetchEvents

### ISSUE THREAD

**Issue by Megamisama** [lbertenasco/ap-ng2-fullcalendar#56]
I really like your angular fullCalendar component but I got an Issue. I got no idea about how to use the refetchEvent that fullCalendar have in its documentation.  Necessary for updating the control in real-time. Thank you for your help.

**Comment by lbertenasco** [comment]
Hi @Megamisama !
To use [refetchEvents](https://fullcalendar.io/docs/event_data/refetchEvents/)
You can try to use CalendarComponent as a ViewChild:
```
import {CalendarComponent} from "ap-angular2-fullcalendar";

export class MyComponent{
  @ViewChild(CalendarComponent) myCalendar: CalendarComponent;

  changeCalendarView(view) {
    this.myCalendar.fullCalendar('refetchEvents');
  }

}
```
