### ISSUE TITLE
 found version 4, expected 3

### ISSUE THREAD

**Issue by Abhay2012** [lbertenasco/ap-ng2-fullcalendar#57]
i want to use full calendar inside my eventsmodule i'm getting this error

Metadata version mismatch for module /home/abhay/Desktop/nxtlife projects/Gulf/node_modules/ap-angular2-fullcalendar/src/calendar/calendar.d.ts, found version 4, expected 3, resolving symbol EventsModule in /home/abhay/Desktop/nxtlife projects/Gulf/src/app/components/events/events.module.ts, resolving symbol EventsModule in /home/abhay/Desktop/nxtlife projects/Gulf/src/app/components/events/events.module.ts

I have tried to update package.json file but still getting same error

**Comment by adessilly** [comment]
I have the same issue since 1.3.5 (1.3.1 works great)

**Comment by lbertenasco** [comment]
@Abhay2012 Are you using Angular5 ?
If not you should stick to the older version.

**Comment by Abhay2012** [comment]
@lbertenasco  thanks for replying..i'm using Angular 4

**Comment by lbertenasco** [comment]
@Abhay2012 Great, you should then stick to version 1.3.1 that still has angular 4.x.x :)
