### ISSUE TITLE
error in metadata version mismatch found version 4 expected 3

### ISSUE THREAD

**Issue by eliakaram93** [lbertenasco/ap-ng2-fullcalendar#59]
ERROR in Metadata version mismatch for module C:/Users/elia/Desktop/appointmentss/appointments/node_modules/ap-angular2-fullcalendar/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/elia/Desktop/appointmentss/appointments/src/app/app.module.ts, resolving symbol AppModule in C:/Users/elia/Desktop/appointmentss/appointments/src/app/app.module.ts

**Comment by lbertenasco** [comment]
Duplicated of: https://github.com/lbertenasco/ap-ng2-fullcalendar/issues/57
