### ISSUE TITLE
Is it possible to have a callback for viewRender

### ISSUE THREAD

**Issue by Mihai-B** [lbertenasco/ap-ng2-fullcalendar#6]
I may be doing something wrong, and I need a litle help here.

How to use the compoenent with the viewRender ( https://fullcalendar.io/docs/display/viewRender/ ) ?

I noticed the component does not provide an output parameter like the initialized one

**Comment by lbertenasco** [comment]
Hi @Mihai-B,
You can add to your `calendarOptions:Object`the property:

```
viewRender: (view, element) =>
                    this.viewRender(view, element),
```

That calls a function inside the scope of your current component.

Does this helps with the issue?

**Comment by Mihai-B** [comment]
Hi @lbertenasco 
Partially.
The problem with this is that if you call another method from the function viewRender it will not work.
I decided in the end to switch to: https://www.primefaces.org/primeng/#/schedule
Thank you for the help

**Comment by lbertenasco** [comment]
You can call another method `this.anotherMethod()` from the function `viewRender`if you use the snippet I shared above.
