### ISSUE TITLE
ap-angular2-fullcalendar

### ISSUE THREAD

**Issue by Madtek** [lbertenasco/ap-ng2-fullcalendar#61]
on version 1.3.5. Agular 4.4.4 
ERROR ... ap-angular2-fullcalendar/index.d.ts, found version 4, expected 3,
Iam not sure how to solve this.

And the install documentation seems not to be up to date.

css setup:
node_modules/fullcalendar/fullcalendar.min.css (doesnt exists)
instead: 
node_modules/fullcalendar/dist/fullcalendar.min.css (exists)

Is this also version mismatch?

**Comment by lbertenasco** [comment]
Hi @Madtek !
Duplicated of: https://github.com/lbertenasco/ap-ng2-fullcalendar/issues/57
