### ISSUE TITLE
Type '"getEventSources"' has no properties in common with type 'Options'

### ISSUE THREAD

**Issue by jmrapp1** [lbertenasco/ap-ng2-fullcalendar#62]
Using ap-angular-calendar 1.3.0 I get this error when trying to build. I think it's stemming from `.fullCalendar` not having a `method: getEventSources` option in the generated `index.d.ts` file

**Comment by lbertenasco** [comment]
Hi @jmrapp1 !
Check the readme, and update to the latest supported version for your angular.
