### ISSUE TITLE
Error when compiling with AOT enabled

### ISSUE THREAD

**Issue by BoyeMagnus** [lbertenasco/ap-ng2-fullcalendar#7]
I am getting the following error when compiling with AOT enabled:

> ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/Magnus/ng-workshop/XXXX/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/Magnus/ng-workshop/XXXX/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/Magnus/ng-workshop/XXXX/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/Magnus/ng-workshop/XXXX/src'
>  @ ./src/main.ts 4:0-74
>  @ multi ./src/main.ts

The error is not showing up when AOT is disabled

**Comment by lbertenasco** [comment]
Hi @BoyeMagnus 
What version of angular-cli & angular are you using?
`ng -v` or `cat package.json | grep @angular`

**Comment by lbertenasco** [comment]
Please try `"ap-angular2-fullcalendar": "1.2.2"`

It should fix the AoT issue :smiley:
