### ISSUE TITLE
 Module ''fullcalendar'' has no exported member 'Options'. in Angular-5 

### ISSUE THREAD

**Issue by AltRoot17** [lbertenasco/ap-ng2-fullcalendar#70]
I'm following your installing  structure step by step , Im used Angular 5 , but  I had following error 

> node_modules/ap-angular2-fullcalendar/src/calendar/calendar.d.ts(3,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(695,36): error TS2304: Cannot find name 'JQueryPromise'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(696,29): error TS2304: Cannot find name 'JQueryPromise'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(697,20): error TS2304: Cannot find name 'JQueryPromise'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(759,22): error TS2304: Cannot find name 'JQueryPromise'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(775,50): error TS2304: Cannot find name 'JQueryPromise'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(988,23): error TS2304: Cannot find name 'JQueryEventObject'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(1401,70): error TS2304: Cannot find name 'JQueryAjaxSettings'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(1603,50): error TS2304: Cannot find name 'JQueryPromise'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(1623,50): error TS2304: Cannot find name 'JQueryPromise'.
> node_modules/fullcalendar/dist/fullcalendar.d.ts(2588,50): error TS2304: Cannot find name 'JQueryPromise'.

how to fix it?

my **index.component.ts
```**
import { Component,  } from '@angular/core';
import 'Fullcalendar';



@Component({
  selector: 'app-index',
  templateUrl: './index.component.html',
  styleUrls: ['./index.component.css']
})
export class IndexComponent  {
  title = 'app';

  calendarOptions:Object = {
    height: 'parent',
    fixedWeekCount : false,
    defaultDate: '2016-09-12',
    editable: true,
    eventLimit: true, // allow "more" link when too many events
    events: [
      {
        title: 'All Day Event',
        start: '2016-09-01'
      },
      {
        title: 'Long Event',
        start: '2016-09-07',
        end: '2016-09-10'
      },
      {
        id: 999,
        title: 'Repeating Event',
        start: '2016-09-09T16:00:00'
      },
      {
        id: 999,
        title: 'Repeating Event',
        start: '2016-09-16T16:00:00'
      },
      {
        title: 'Conference',
        start: '2016-09-11',
        end: '2016-09-13'
      },
      {
        title: 'Meeting',
        start: '2016-09-12T10:30:00',
        end: '2016-09-12T12:30:00'
      },
      {
        title: 'Lunch',
        start: '2016-09-12T12:00:00'
      },
      {
        title: 'Meeting',
        start: '2016-09-12T14:30:00'
      },
      {
        title: 'Happy Hour',
        start: '2016-09-12T17:30:00'
      },
      {
        title: 'Dinner',
        start: '2016-09-12T20:00:00'
      },
      {
        title: 'Birthday Party',
        start: '2016-09-13T07:00:00'
      },
      {
        title: 'Click for Google',
        url: 'http://google.com/',
        start: '2016-09-28'
      }
    ]
  };

  onCalendarInit(initialized: boolean) {
    console.log('Calendar initialized');
  }

}

```webpack: Failed to compile.

**Comment by AltRoot17** [comment]
FINALLY  I Found some solution now its work for me, Im Updated to `npm install fullcalendar@3.6.1`
-- | --

**Comment by shanemac10** [comment]
I was getting this error, even though my version in the package.json showed 3.6.1, but I ran `npm install fullcalendar@3.6.1` anyway and it fixed the problem. Hope this helps!

**Comment by anantksingh** [comment]
After install npm install fullcalendar@3.7.0 --save i am getting issue "Module ''fullcalendar'' has no exported member 'Options'." In angular 8

**Comment by lbertenasco** [comment]
There is no support for angular 8. Sorry.

**Comment by anantksingh** [comment]
Ok Thanks

**Comment by anantksingh** [comment]
How to use dayRender event(callback) in angular 7
