### ISSUE TITLE
regression when update form 1.3.5 to 1.3.7

### ISSUE THREAD

**Issue by liuminHU** [lbertenasco/ap-ng2-fullcalendar#72]
hi,

I have a problem when upgrade from 1.3.5 to 1.3.7, the view is not updated immediately after value changed. you need trigger the change with a click somewhere by example.

I have code like 
```javascript
this.calendarOptions.dayClick = (date, jsEvent, view) => this.onSelectDay(date, jsEvent, view);


  onSelectDay(date, jsEvent, view) {
this.title = 'toto';
    }
  ```
then something like this in html :
{{ title }}

here is my angular version : 
![image](https://user-images.githubusercontent.com/22397357/34408105-214b038a-ebc2-11e7-8008-fadb240c92fb.png)

**Comment by louisl** [comment]
Did you figure this out? I have the same problem when clicking an event.

**Comment by lbertenasco** [comment]
Hi @liuminHU and @louisl !
I'm unable to reproduce this issue.

Try using `ChangeDetectorRef`:
```
constructor(private ref: ChangeDetectorRef) {
    ...
      this.ref.detectChanges();
    ...
```

**Comment by terminaltor** [comment]
ChangeDetectorRef did solve the problem... thanks @lbertenasco
