### ISSUE TITLE
ngDevMode + ɵmakeDecorator Error

### ISSUE THREAD

**Issue by Meistercoach83** [lbertenasco/ap-ng2-fullcalendar#76]
Hi! I´m trying to add the calendar to my app. When I saved it, travis CI gave me the following error message:

> ERROR in ../ap-angular2-fullcalendar/src/calendar/calendar.ts(14,2): Error during template compile of 'CalendarComponent'
>   Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Component'
>     'Component' calls 'ɵmakeDecorator'.
> node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
> node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

How can I get it to work?

**Comment by lbertenasco** [comment]
Hi @Meistercoach83 !
Could you check this other issues related to AoT compilation and the `emakeDecorator` issue?
https://github.com/lbertenasco/ap-ng2-fullcalendar/issues?utf8=%E2%9C%93&q=%C9%B5makeDecorator+
Let me know if any of those helped you :)
And feel free to re-open the issue if you have more details about your problem

**Comment by Meistercoach83** [comment]
Hi @lbertenasco, the given tipps didnt work. 
Im on angular 6.0.0.rc-3

**Comment by lbertenasco** [comment]
Ok, give me a couple of minutes to update and test on the demo project :)

**Comment by lbertenasco** [comment]
It's working on my end.
Please check the [demo repo](https://github.com/lbertenasco/ap-ng2-fullcalendar-demo)
```bash
 ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.3
Node: 7.10.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular/tsc-wrapped: error
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by Meistercoach83** [comment]
@lbertenasco when I delete the angular folder in ap-angular-fullcalendar/node_modules, everything is working again.

>   Angular CLI: 6.0.0-rc.4
      Node: 9.11.1
      OS: win32 x64
      Angular: 6.0.0-rc.5
      ... animations, common, compiler, compiler-cli, core, forms
      ... language-service, platform-browser, platform-browser-dynamic
      ... router, service-worker
      Package                           Version
      -----------------------------------------------------------
      @angular-devkit/architect         0.5.6
      @angular-devkit/build-angular     0.5.6
      @angular-devkit/build-optimizer   0.5.6
      @angular-devkit/core              0.5.6
      @angular-devkit/schematics        0.5.6
      @angular/cdk                      5.2.4
      @angular/cli                      6.0.0-rc.4
      @angular/flex-layout              5.0.0-beta.14-17a70ee
      @angular/http                     5.2.9
      @angular/material                 5.2.4
      @ngtools/json-schema              1.1.0
      @ngtools/webpack                  6.0.0-rc.4
      @schematics/angular               0.5.6 
      @schematics/update                0.5.6
      rxjs                              6.0.0-uncanny-rc.7
      typescript                        2.7.2
      webpack                           4.5.0

**Comment by elenafedorets** [comment]
@lbertenasco your example works, because you tested with Angular CLI: 1.7.3 , but if you try with Angular CLI: 6.0.0 it won't work . @Meistercoach83 was right, if I will delete the angular folder  in ap-angular-fullcalendar/node_modules - everything will be ok, but it's not good solution. Can you help us to resolve this problem?

**Comment by lbertenasco** [comment]
Hi @elenafedorets !
Have you installed the dependency before or after upgrading your angular to v6?

I haven't tested the library with angular6.
But you'll need to re-build all your packages after upgrading your angular versions.

**Comment by elenafedorets** [comment]
Hi @lbertenasco, thank you for update!

**Comment by lbertenasco** [comment]
@elenafedorets you can now try version `1.6.4` that comes with Angular 6!

Hope this helps, feel free to re-open the issue if you encounter any other problems.
