### ISSUE TITLE
no exported member 'Options'

### ISSUE THREAD

**Issue by Bari77** [lbertenasco/ap-ng2-fullcalendar#77]
Hello,

I use your plugin for my website project in Angular 4, but I got the following error :
![image](https://user-images.githubusercontent.com/20283367/38955445-fd930ae2-4354-11e8-88c2-902c9aeebb3e.png)
I guess you need to update your fullcalendar version to 3.9.0 (the last) and adapt this.

PS: To resolve the actual error, we need to use the same FullCalendar version as this plugin (3.6.2).
Cordialy, Bari.

**Comment by lbertenasco** [comment]
Hi @Bari77 !
I've updated the package to support angular 6 and the latest version of fullcalendar.
Please upgrade the package to version `1.6.4`
Cheers!
