### ISSUE TITLE
Error in during production build.

### ISSUE THREAD

**Issue by lanzosuarez** [lbertenasco/ap-ng2-fullcalendar#8]
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the func
tion or lambda with a reference to an exported function, resolving symbol Injectable in C:/Users/user/Documents/PONS FILES/WORK/KMC_SOLUTIONS_1/kmc-admin/kmcwe
bsite/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in C:/Users/user/Documents/PONS FILES/WORK/KMC_SOLUTIONS_
1/kmc-admin/kmcwebsite/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in C:/Users/user/Documents/PONS FILES/WO
RK/KMC_SOLUTIONS_1/kmc-admin/kmcwebsite/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\user\Documents\PONS FILES\WORK\KMC_SOLUTIONS_1\kmc-admin\kmcwebsite\
src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

Is there any fixed with this?

**Comment by lbertenasco** [comment]
Hi @lanzosuarez What version of `angular` and `ap-ng2-fullcalendar` are you using?

**Comment by lanzosuarez** [comment]
@lbertenasco i saw your comment from one of the closed issues. i did what you said by installing 1.2.2. and it is fixed now. thank you for the response though 😄

**Comment by lbertenasco** [comment]
@lanzosuarez haha good to know it's fixed!
Closing the issue :)
[fix](https://github.com/lbertenasco/ap-ng2-fullcalendar/issues/7#issuecomment-294505403)
