### ISSUE TITLE
It does not look properly

### ISSUE THREAD

**Issue by pookdeveloper** [lbertenasco/ap-ng2-fullcalendar#81]
In Ionic 3 it view like this:

![image](https://user-images.githubusercontent.com/3384734/40885832-35163942-672e-11e8-974f-32792839041a.png)

**Comment by lbertenasco** [comment]
Hi @pookdeveloper I've never tried it out on Ionic3.
Can you provide a sample repository so I can check the issue properly?

Thanks!

**Comment by pookdeveloper** [comment]
hi @lbertenasco I test on windows and I get this error ,

typescript: ...OS/ionic/ionic3-calendar/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts, line: 9
            Cannot redeclare block-scoped variable 'ngDevMode'.

I put the code in this repo:
https://github.com/pookdeveloper/ionic3-calendar

Thanks

**Comment by lbertenasco** [comment]
@pookdeveloper you are using a wrong package version.
Please check the README.md to get the correct package for your angular version.

**Comment by pookdeveloper** [comment]
@lbertenasco  ok i change the version but anytimes work without styles and others i get this error:

![image](https://user-images.githubusercontent.com/3384734/40973999-8033fb78-68c6-11e8-9436-3b78819ae673.png)

What im doing wrong ? I update the code at the repo.

Thanks

**Comment by lbertenasco** [comment]
Hi @pookdeveloper !

Could you please try this solution https://github.com/lbertenasco/ap-ng2-fullcalendar/issues/70 ?

**Comment by pookdeveloper** [comment]
Hi @lbertenasco  now it works but i dont see the styles, I update the code of the repo. (https://github.com/pookdeveloper/ionic3-calendar/tree/5e608a59e2f14a8d1a65d7b4ff321184b3545794)

https://github.com/pookdeveloper/ionic3-calendar

Thanks

**Comment by pookdeveloper** [comment]
Hi @lbertenasco I can put the file creating a config file what I add in the package.json

I update the code of the repo. (https://github.com/pookdeveloper/ionic3-calendar/tree/bac9464d19b2ec1968ffbb792bb993764e25b2ed)
https://github.com/pookdeveloper/ionic3-calendar

The are other solution ? Thanks

**Comment by lbertenasco** [comment]
@pookdeveloper does it work when you manually add the css? 
Because that's probably what you need to do.
If it doesn't work I'm not sure what can be done to fix it sorry.

**Comment by pookdeveloper** [comment]
@lbertenasco  if i get the code and I add  in my file.css it works, but if you wnat to import the file are in node_modules for ionic it's  necessary do a config and put in the package.json.

Thanks for everything, the last commit (https://github.com/pookdeveloper/ionic3-calendar/tree/bac9464d19b2ec1968ffbb792bb993764e25b2ed)
https://github.com/pookdeveloper/ionic3-calendar) is for solved the depency of css in  Ionic , in angular its not necesary genereate a custom config.

Regards
