### ISSUE TITLE
Issue and customization

### ISSUE THREAD

**Issue by scssat** [lbertenasco/ap-ng2-fullcalendar#82]
Hi,
I have an issue with Angular 6 and Fullcalendar. I also want to hire U to do some customization. Pls. send me an e-mail ASAP on scssat@gmail.com so I can elaborate.

**Comment by lbertenasco** [comment]
Hi @scssat !
Do you have any more details about the issue with angular 6?
Is an issue with this library?

Thanks about the job offer but I'm not doing freelance work at the moment.

I'm closing this issue, feel free to re-open it with more details.
