### ISSUE TITLE
Issue with dialog

### ISSUE THREAD

**Issue by scssat** [lbertenasco/ap-ng2-fullcalendar#83]
When I try to open a material design dialog, or ng-bootstrap modal from an event, say select or eventClick the modal/dialog does not work, nothing behaves as expected. Events, input fields etc. 

I found a recent similar issue on SO: https://stackoverflow.com/questions/51810372/mat-dialog-that-is-used-in-fullcalendar-opens-twice/52599787#52599787

**Comment by louisl** [comment]
I had the same issue with Bootstrap, thought it was some kind of scope issue, I tried the ngZone fix mentioned in your link above and it works for me.

In calendar options I have:
```typescript
eventClick: this.eventClick.bind(this),
```
Then my eventClick function like so
```typescript
  public eventClick (calendarEvent: any, jsEvent: Event, view: any): void {
    this.ngZone.run(() => {
      // Open modal or whatever here.
    })
  }
```
