### ISSUE TITLE
Update to Angular 7

### ISSUE THREAD

**Issue by Shatts** [lbertenasco/ap-ng2-fullcalendar#86]
After updating app to Angular 7 an error showed up.
`ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

**Comment by lbertenasco** [comment]
Hi @Shatts !
Yes, I'll add support for Angular 7 on the next release.

I'll keep the issue open until resolved.

**Comment by lbertenasco** [comment]
Hey @Shatts !
Please try installing version`1.7.0`
`npm i --save -E ap-angular-fullcalendar@1.7.0`
Let me know if it works and I'll do the official release :)

**Comment by conlaoch1** [comment]
im having the same issue - glad you're already working on it / fixed it! :)

**Comment by Shatts** [comment]
Hey @lbertenasco 
After installing I got another issue(
`ERROR in ./node_modules/ap-angular-fullcalendar/index.ts
Module build failed: Error: /home/user/portal-front-v2/node_modules/ap-angular-fullcalendar/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/portal-front-v2/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (/home/user/portal-front-v2/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by androidseb25** [comment]
Same issue by me

`ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

**Comment by conlaoch1** [comment]
same here.

**Comment by freefred81** [comment]
same here!!!

**Comment by lbertenasco** [comment]
Hey! @fscamuzzi2 @conlaoch1 @androidseb25 @Shatts 😃 

I've released a new version that should fix the issue! 

Please update to `ap-angular-fullcalendar@1.7.10`.

If you need, you can check the demo project here: https://github.com/lbertenasco/ap-ng2-fullcalendar-demo

And this is the update commit: https://github.com/lbertenasco/ap-ng2-fullcalendar-demo/commit/17d28b634d8b9af072d565bffaf1e99621493628

Feel free to re-open the issue if you encounter any other problems.
