### ISSUE TITLE
Angular don´t reading CSS and JavaScript files

### ISSUE THREAD

**Issue by Nesbox314** [lbertenasco/ap-ng2-fullcalendar#87]
I tried to import them in every possible way, but they do not carry it at all! CSS fills in with the calendar and JavaScript just does not work!
![capturar](https://user-images.githubusercontent.com/46055626/50358287-e71c9780-053f-11e9-85c2-db528951492a.PNG)

More deitailed code in StackOverflow: https://stackoverflow.com/questions/53889153/angular-6-fullcalendar-is-not-loading-correctly

**Comment by lbertenasco** [comment]
Hey @Nesbox314 !
Have you tried with: 
https://github.com/lbertenasco/ap-ng2-fullcalendar-demo 
Please let me know if this helps! And re-open the issue!
