### ISSUE TITLE
StaticInjectorError(AppModule)[CalendarComponent -> ElementRef] Angular 8

### ISSUE THREAD

**Issue by Eye-t** [lbertenasco/ap-ng2-fullcalendar#89]
I have an issue with the fullcalendar schedular. I recently updated my project to angular 8.2.0 and it throws an error in the browser.
I'm using 'CalendarModule' from the 'ap-angular-fullcalendar'

This is the error:
![image](https://user-images.githubusercontent.com/44054292/62855083-84a42180-bcf1-11e9-884c-368a776f9bbd.png)

This is my package.json:
"dependencies": {
    "@agm/core": "1.0.0-beta.6",
    "@angular/animations": "^8.2.0",
    "@angular/common": "^8.2.0",
    "@angular/compiler": "^8.2.0",
    "@angular/core": "^8.2.0",
    "@angular/forms": "^8.2.0",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^8.2.0",
    "@angular/platform-browser-dynamic": "^8.2.0",
    "@angular/platform-server": "^8.2.0",
    "@angular/router": "^8.2.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.1",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "@swimlane/ngx-charts": "6.0.0",
    "@swimlane/ngx-datatable": "git+https://github.com/zackarychapple/ngx-datatable.git",
    "angular": "^1.7.8",
    "angular-calendar": "0.27.11",
    "angular-jsvat": "^1.1.0",
    "angular-tree-component": "3.8.0",
    "angular2-text-mask": "8.0.2",
    "ap-angular-fullcalendar": "^1.7.10",
    "ap-angular2-fullcalendar": "^1.6.4",
    "big-integer": "^1.6.24",
    "bootstrap": "^4.3.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "2.4.1",
    "d3": "^4.8.0",
    "devextreme": "^17.1.7",
    "devextreme-angular": "^17.1.7",
    "dragula": "3.7.2",
    "fullcalendar": "^3.10.0",
    "intl": "^1.2.5",
    "jquery": "^3.3.1",
    "moment": "^2.24.0",
    "ng-select": "^1.0.2",
    "ng-sidebar": "6.0.1",
    "ng2-archwizard": "^2.1.0",
    "ng2-dragula": "1.5.0",
    "ng2-file-upload": "^1.2.1",
    "ng2-validation": "4.2.0",
    "ngx-color-picker": "^4.5.3",
    "quill": "1.2.6",
    "resize-observer-polyfill": "^1.4.2",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "screenfull": "3.3.1",
    "spinthatshit": "^1.0.4",
    "text-mask-addons": "3.6.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.802.1",
    "@angular/cli": "^8.2.0",
    "@angular/compiler-cli": "^8.2.0",
    "@angular/language-service": "8.2.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.3.31",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "3.5.3"
  }

This is the import in my app.module.ts:
imports: [
    SharedModule,
    BrowserModule,
    SelectModule,
    ArchwizardModule,
    BrowserAnimationsModule,
    RouterModule.forRoot(AppRoutes),
    FormsModule, ReactiveFormsModule,
    HttpModule,
    HttpClientModule,
    NgxDatatableModule,
    NgbModule.forRoot(),
    SidebarModule.forRoot(),
    ColorPickerModule,
    DxTooltipModule,
    CalendarModule
  ],

Anyone who can solve this problem?
Thanks in advance!

**Comment by lbertenasco** [comment]
Hey @Eye-t this repo does not support angular 8. Sorry.
It's not being maintained anymore.
