### ISSUE TITLE
Cant build AOT emakeDecorator

### ISSUE THREAD

**Issue by jfillipe** [lbertenasco/ap-ng2-fullcalendar#9]
I saw everything about this, and i cannot resolve.
Please, help-me to fix that.

In app.module, i try 2 ways
@NgModule.imports[CalendarModule.forRoot()...]

and declarations[CalendarComponent..]

Both works correct in DEV mode, but AOT not...

My versions:
"ap-angular2-fullcalendar": "^1.2.7"
ng -v
@angular/cli: 1.0.2
node: 7.8.0
os: win32 x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/compiler-cli: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/platform-server: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.2

And the error is:

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider repla
cing the function or lambda with a reference to an exported function, resolving symbol Injectable in C:/Desenv/app/SAM-Front/node_modules/ap-angul
ar2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in C:/Desenv/app/SAM-Front/node_modules/ap-angular2-fullcalendar/node_m
odules/@angular/core/core.d.ts, resolving symbol ɵf in C:/Desenv/app/SAM-Front/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/co
re.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Desenv\app\SAM-Front\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

Thank you for any help =)

**Comment by lbertenasco** [comment]
Hi @jfillipe try upgrading to `angular: 4.1.1` on your project :)

**Comment by jfillipe** [comment]
Hi @lbertenasco ... i´ve updated and nothing =(

@angular/cli: 1.0.2
node: 7.8.0
os: win32 x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/compiler-cli: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/platform-server: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2

Can i cry?

**Comment by lbertenasco** [comment]
@jfillipe please do not cry :joy: 

Try to do `rm -r node_modules/ && npm i`.

this is my working AoT config on a v `1.2.7` sample project
```
@angular/cli: 1.0.2
node: 7.10.0
os: linux x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1
@angular/language-service: 4.1.1
```
Let me know if that helped.
If not you can try installing using [yarn](https://yarnpkg.com/en/docs/install)
PD: it's more reliable and faster than npm

**Comment by jfillipe** [comment]
@lbertenasco  Yeahhh!!! That´s work!

Thank you very much!!! Thanks!!!

**Comment by lbertenasco** [comment]
@jfillipe Good to hear that!
Closing the issue :smiley:
