### ISSUE TITLE
angular 8 upgrade

### ISSUE THREAD

**Issue by Adambs** [lbertenasco/ap-ng2-fullcalendar#90]
Hi, 

I upgraded my angular version to 8 and the only problem I left with is the calendar module. Please assist ASAP

My env: 

Angular CLI: 8.3.4
Node: 10.16.3
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/flex-layout              8.0.0-beta.27
@angular/http                     7.2.15
@angular/language-service         5.0.1
@angular/material                 8.2.0
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.40.2

Errors:

Date: 2019-09-14T12:06:29.903Z - Hash: ad6329492544a8bbb53c - Time: 41331ms

ERROR in ../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:695:36 - error TS2304: Cannot f              ind name 'JQueryPromise'.

695      construct: (executor: any) => JQueryPromise<{}>;
                                       ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:696:29 - error TS2304: Cannot find name               'JQueryPromise'.

696      resolve: (val: any) => JQueryPromise<{}>;
                                ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:697:20 - error TS2304: Cannot find name               'JQueryPromise'.

697      reject: () => JQueryPromise<{}>;
                       ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:759:22 - error TS2304: Cannot find name               'JQueryPromise'.

759      whenReleased(): JQueryPromise<{}>;
                         ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:775:50 - error TS2304: Cannot find name               'JQueryPromise'.

775      fetch(start: any, end: any, timezone: any): JQueryPromise<{}>;
                                                     ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:988:23 - error TS2304: Cannot find name               'JQueryEventObject'.

988      windowResize(ev: JQueryEventObject): void;
                          ~~~~~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:1401:70 - error TS2304: Cannot find name               'JQueryAjaxSettings'.

1401  export interface EventSourceExtendedInput extends EventOptionsBase, JQueryAjaxSettings {
                                                                          ~~~~~~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:1608:50 - error TS2304: Cannot find name               'JQueryPromise'.

1608      fetch(start: any, end: any, timezone: any): JQueryPromise<{}>;
                                                      ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:1628:50 - error TS2304: Cannot find name               'JQueryPromise'.

1628      fetch(start: any, end: any, timezone: any): JQueryPromise<{}>;
                                                      ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts:2614:50 - error TS2304: Cannot find name               'JQueryPromise'.

2614      fetch(start: any, end: any, timezone: any): JQueryPromise<{}>;
                                                      ~~~~~~~~~~~~~
../node_modules/ap-angular2-fullcalendar/src/calendar/calendar.d.ts:3:10 - error TS2305: Module '"fullcalendar"' has no exported m              ember 'Options'.

3 import { Options } from "fullcalendar";
           ~~~~~~~

**Comment by lbertenasco** [comment]
There is no support for angular 8.

**Comment by Adambs** [comment]
I solved all the issues. The only problem I left with is the following exception, please take a look I have a feeling it's not necessarily related to angular 8 version. 

SolutionsComponent.html:71 ERROR NullInjectorError: StaticInjectorError(AppModule)[CalendarComponent -> ElementRef]: 
  StaticInjectorError(Platform: core)[CalendarComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4200/vendor.js:68857:25)
    at resolveToken (http://localhost:4200/vendor.js:80049:24)
    at tryResolveToken (http://localhost:4200/vendor.js:79993:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:79895:20)
    at resolveToken (http://localhost:4200/vendor.js:80049:24)
    at tryResolveToken (http://localhost:4200/vendor.js:79993:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:79895:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:88365:29)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (http://localhost:4200/vendor.js:89036:16)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:88365:29)
